services:
  backend:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend/simsy:/usr/src/app/simsy
      - ./data/db.sqlite3:/usr/src/data/db.sqlite3
    env_file: "backend/simsy/.env"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/app
      - ./frontend/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt              # Mount Certbot configs and certificates
      - ./data/certbot/www:/var/www/certbot               # Mount webroot for Certbot challenges
      - ./data/media:/usr/src/data/media:ro
      - ./data/videos:/usr/src/data/videos:ro
      - ./backend/simsy/staticfiles:/usr/src/app/simsy/staticfiles:ro
    env_file: "frontend/.env"
    restart: always
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt              # Same volume as Nginx for certificates
      - ./data/certbot/www:/var/www/certbot               # Same volume as Nginx for webroot challenges
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # Use --staging for testing (in the command below) to avoid hitting Let's Encrypt rate limits
    # Remove --staging for producing certificates
    command: certonly --webroot -w /var/www/certbot --email youssefihab33@gmail.com --agree-tos --no-eff-email -d simsy.redirectme.net
